### ISSUE TITLE
`yield_fixture` is deprecated in pytest 3.x

### ISSUE THREAD

**Issue by lbolla** [jaraco/jaraco.postgres#6]
https://github.com/jaraco/jaraco.postgres/blob/c71dc18a9e49aaeca88b54eff16540b9592e3d8d/jaraco/postgres/fixtures.py#L7

See https://docs.pytest.org/en/latest/yieldfixture.html?highlight=yield_fixture

**Comment by jaraco** [comment]
That's odd - because I'm not yet seeing any deprecation warnings about it, even on pytest 4.x. No big deal - easy to fix.
